In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('scFv_from_ANDD_dataset_wu_et_al.csv', sep=';')
df

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance
0,UNIPROT_nano,2024-09-08 00:00:00,3J5M,No,ELECTRON MICROSCOPY,Cryo-EM structure of the BG505 SOSIP.664 HIV-1 Env trimer with 3 PGV04 Fabs,VRAI,scFv,Homo sapiens,4.0,"D, H, L","D, H, L",NaN,NaN,9478.0,100.0,PGV04 heavy chain,3.0,"C, G, K","C, G, K",NaN,NaN,10210.0,100.0,PGV04 light chain,1.0,"A, E, I","A, E, I",UniProt,Q2N0S6,\,\,Human immunodeficiency virus 1,no,QVQLVQSGSGVKKPGASVRVSCWTSEDIFERTELIHWVRQAPGQGLEWIGWVKTVTGAVNFGSPDFRQRVSLTRDRDLFTAHMDIRGLTQGDTATYFCARQKFYTGGQGWYFDLWGRGTLIVVSS,EIVLTQSPGTLSLSPGETASLSCTAASYGHMTWYQKKPGQPPKLLIFATSKRASGIPDRFSGSQFGKQYTLTITRMEPEDFARYYCQQLEFFGQGTRLEIR,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_nano|PDB|schema_harmonisation
1,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
2,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
3,UNIPROT_nano,2024-09-08 00:00:00,3V7A,No,X-RAY DIFFRACTION,Structural basis for broad detection of genogroup II noroviruses by a monoclonal antibody that binds to a site occluded in the viral particle,VRAI,scFv,unknown,1.0,"A, C","E, F",NaN,NaN,995243.0,100.0,5B18 heavy chain,2.0,"B, D","G, H",NaN,NaN,995371.0,100.0,5B18 kappa chain,3.0,"E, F","A, B",UniProt,Q5F4T5,\,\,Norovirus isolates,no,QVQLQQSGAELVRPGTSVKVSCKASGYAFTNYLIEWVKQRPGQGLEWIGVINPRSGDTNSNEKFKGKAILTADKSSSTAYMQLSSLTSDDSAVYFCARSGTTAYFAMDYWGQGTSVTVSS,DIQMTQSPASLSASVGETVTITCRASENIYSYLAWYQQKQGKSPQLLVYNVKTLAEGVPSRFSGSGSGTQFSLKINSLQPEDFGSYYCQHHYGSPPWTFGGGTKLEIK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_nano|PDB|schema_harmonisation
4,INDI_structure_sequence,2024-05-13 00:00:00,4KRO,No,X-RAY DIFFRACTION,Nanobody/VHH domain EgA1 in complex with the extracellular region of EGFR,VRAI,scFv,Mus musculus,4.0,D,D,NaN,NaN,16953.0,100.0,Cetuximab heavy chain,3.0,C,C,NaN,NaN,1608.0,100.0,Cetuximab light chain,1.0,A,A,UniProt,P00533,\,\,Homo sapiens,no,QVQLQESGGGLVQPGGSLRLSCAASGRTFSSYAMGWFRQAPGKQREFVAAIRWSGGYTYYTDSVKGRFTISRDNAKTTVYLQMNSLKPEDTAVYYCAATYLSSDYSRYALPQRPLDYDYWGQGTQVTVSS,DILLTQSPVILSVSPGERVSFSCRASQSIGTNIHWYQQRTNGSPRLLIKYASESISGIPSRFSGSGSGTDFTLSINSVESEDIADYYCQQNNNWPTTFGAGTKLELKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNR,GRTFSSYA,IRWSGGYT,AATYLSSDYSRYALPQRPLDYDY,\,\,\,IMGT,NaN,NaN,NaN,not_reported,\,INDI_structure_sequence|PDB|schema_harmonisation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,UNIPROT_ab,16/09/2018 00:00,NaN,NaN,ELECTRON MICROSCOPY,Cryo-EM structure of cenerimod -bound Sphingosine-1-phosphate receptor 1 in complex with Gi protein,VRAI,scFv,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_ab|PDB|schema_harmonisation
117,UNIPROT_ab,16/09/2018 00:00,NaN,NaN,ELECTRON MICROSCOPY,Cryo-EM structure of ozanimod -bound Sphingosine-1-phosphate receptor 1 in complex with Gi protein,VRAI,scFv,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_ab|PDB|schema_harmonisation
118,UNIPROT_ab,16/09/2018 00:00,NaN,NaN,ELECTRON MICROSCOPY,Cryo-EM structure of SEW2871-bound Sphingosine-1-phosphate receptor 1 in complex with Gi protein,VRAI,scFv,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_ab|PDB|schema_harmonisation
119,UNIPROT_ab,16/09/2018 00:00,NaN,NaN,ELECTRON MICROSCOPY,Structure of a D2 dopamine receptor-G-protein complex in a lipid membrane,VRAI,scFv,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_ab|PDB|schema_harmonisation
120,UNIPROT_ab,16/09/2018 00:00,NaN,NaN,ELECTRON MICROSCOPY,Cryo-EM structure of BG505.SOSIP.664 in complex with BF520.1 antigen binding fragment,VRAI,scFv,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,QVQLVQSGAEMKMPGASVKVSCKASGYTFTGNYIHWVRQAPGQGLEWMGWIAPHSGDTSYAQRFQGRVTMTGDTSLSTAYMELSRLRSDDTAVYYCARGPFPNYYGPGSYWGGLDFWGQGTLVSVSS,EIVMTQSPATLSVSLGERATLSCRTSQNVAYNFAWYQQKPGQAPRLLIYEASSRATGTPARFSGSGFGTEFTLTISSMQSEDFAVYYCQQYNNWPSPFTFGPGTKVHIK,\,\,\,\,\,\,\,NaN,NaN,NaN,not_reported,\,UNIPROT_ab|PDB|schema_harmonisation

In [4]:
list(df.columns)

['Source',
 'Update_Date',
 'PDB_ID',
 'PDB_ID_Changed',
 'Experimental_Method',
 'Structure_Title',
 'Complex_Structure',
 'Ab_or_Nano',
 'Source_Organism',
 'H_Chain Entity ID',
 'H_Chain Asym ID',
 'H_Chain Auth Asym ID',
 'H_Chain Database Name',
 'H_Chain Accession Code(s)',
 'H_Chain Sequence Cluster ID',
 'H_Chain Sequence Cluster Identity Threshold',
 'H_Chain Macromolecule Name',
 'L_Chain Entity ID',
 'L_Chain Asym ID',
 'L_Chain Auth Asym ID',
 'L_Chain Database Name',
 'L_Chain Accession Code(s)',
 'L_Chain Sequence Cluster ID',
 'L_Chain Sequence Cluster Identity Threshold',
 'L_Chain Macromolecule Name',
 'Ag_Entity ID',
 'Ag_Asym ID',
 'Ag_Auth Asym ID',
 'Ag_Database Name',
 'Ag_Accession Code(s)',
 'Ag_Name',
 'Ag_Seq',
 'Ag_Source Organism',
 'Ab/Nano_Mutation',
 'Ab/Nano H_Chain AA',
 'Ab/Nano L_Chain AA',
 'Ab/Nano_CDR H1',
 'Ab/Nano_CDR H2',
 'Ab/Nano_CDR H3',
 'Ab/Nano_CDR L1',
 'Ab/Nano_CDR L2',
 'Ab/Nano_CDR L3',
 'CDR Nomenclature',
 'Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)',
 '∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )',
 'Affinity_Method',
 'Reason_Code',
 'Predicted_or_Not',
 'Provenance']

In [5]:
df[~(df['Ab/Nano_CDR H1'] == "\\") & ~(df['Ab/Nano_CDR L1'] == "\\")][:3]

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance
1,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
2,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
12,SabDab_nano,\,5EOC,No,X-RAY DIFFRACTION,Crystal structure of Fab C2 in complex with a Cyclic variant of Hepatitis C Virus E2 epitope I,VRAI,scFv,Mus musculus,3.0,C,J,NaN,NaN,170146.0,100.0,Fab fragment (Heavy chain),2.0,"B, D","L, M",NaN,NaN,170143.0,100.0,Fab fragment (Light chain),4.0,"E, F","P, Q",UniProt,P27958,ala-cys-gln-leu-ile-asn-thr-asn-gly-ser-trp-his-ile-cys,ACQLINTNGSWHIC,Hepacivirus hominis,no,EVQLQQPGAELVRPGGSVKLSCKASGYSFTTYWMMWVKQRPGQGLEWIGMIQPSDSETRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARTGRGDAWLTYWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCRASKSVSTSGYSYMHWYQQKPGQPPRLLLYLGSNLESGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCQHIRELTRSFGGGTKLEIK,GYSFTTY,QPSDSE,TGRGDAWLTY,RASKSVSTSGYSYMH,LGSNLES,QHIRELTRS,Chothia,3.03E-08,"-10,25714745",NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm

In [6]:
df_to_save = df[~(df['Ab/Nano_CDR H1'] == "\\") & ~(df['Ab/Nano_CDR L1'] == "\\")].reset_index(drop=True)
df_to_save

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
2,SabDab_nano,\,5EOC,No,X-RAY DIFFRACTION,Crystal structure of Fab C2 in complex with a Cyclic variant of Hepatitis C Virus E2 epitope I,VRAI,scFv,Mus musculus,3.0,C,J,NaN,NaN,170146.0,100.0,Fab fragment (Heavy chain),2.0,"B, D","L, M",NaN,NaN,170143.0,100.0,Fab fragment (Light chain),4.0,"E, F","P, Q",UniProt,P27958,ala-cys-gln-leu-ile-asn-thr-asn-gly-ser-trp-his-ile-cys,ACQLINTNGSWHIC,Hepacivirus hominis,no,EVQLQQPGAELVRPGGSVKLSCKASGYSFTTYWMMWVKQRPGQGLEWIGMIQPSDSETRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARTGRGDAWLTYWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCRASKSVSTSGYSYMHWYQQKPGQPPRLLLYLGSNLESGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCQHIRELTRSFGGGTKLEIK,GYSFTTY,QPSDSE,TGRGDAWLTY,RASKSVSTSGYSYMH,LGSNLES,QHIRELTRS,Chothia,3.03E-08,"-10,25714745",NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm
3,SabDab_nano,2019-01-29 00:00:00,6QKD,No,X-RAY DIFFRACTION,CRYSTAL STRUCTURE OF vhh-based FAB-fragment of antibody BCD-085,VRAI,scFv,Lama glama,1.0,"A, B, C, D","H, I, J, K",NaN,NaN,1019893.0,100.0,FAB HEAVY CHAIN,2.0,"E, F, G, H","L, M, O, T",NaN,NaN,1019895.0,100.0,FAB LIGHT CHAIN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,QVQLVQSGGGLVQAGGSLRLSCAASGGTFATSPMGWLRQAPGKGTEFVAAISPSGGDRIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCAVRRRFDGTSYYTGDYDSWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYDASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYSYSPVTFGQGTKVEIK,GGTFATSP,ISPSGGDR,AVRRRFDGTSYYTGDYDS,RASQSVSSSYLA,DASSRAT,QQYSYSPVT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
4,SabDab_nano,2020-06-21 00:00:00,6ZH9,No,X-RAY DIFFRACTION,Ternary complex CR3022 H11-H4 and RBD (SARS-CoV-2),VRAI,scFv,Homo sapiens,1.0,A,HHH,NaN,NaN,94476.0,100.0,CR3022 heavy,2.0,B,LLL,NaN,NaN,2814.0,100.0,CR3022 Light chain,1.0,A,HHH,NaN,NaN,unknown,ITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPK,Homo sapiens,no,QVQLVESGGGLMQAGGSLRLSCAVSGRTFSTAAMGWFRQAPGKEREFVAAIRWSGGSAYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCAQTHYVSYLLSDYATWPYDYWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCKSSQSVLYSSINKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTPYTFGQGTKVEIK,GRTFSTAA,IRWSGGSA,AQTHYVSYLLSDYATWPYDY,KSSQSVLYSSINKNYLA,WASTRES,QQYYSTPYT,Chothia,6.594088e-06,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm
5,SabDab_nano,\,7F4H,No,ELECTRON MICROSCOPY,"Cryo-EM structure of afamelanotide-bound melanocortin-1 receptor in complex with Gs protein, Nb35 and scFv16",VRAI,scFv,synthetic construct,3.0,C,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,G,UniProt,P59768,\,MASNNTASIAQARKLVEQLKMEANIDRIKVSKAAADLMAYCEAHAKEDPLLTPVPASENPFREKKFFCAIL/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGADNSGKSTIVKQMRIYHVNGYSEEECKQYKAVVYSNTIQSIIAIIRAMGRLKIDFGDSARADDARQLFVLAGAAEEGFMTAELAGVIKRLWKDSGVQACFNRSREYQLNDSAAYYLNDLDRIAQPNYIPTQQDVLRTRVKTSGIFETKFQVDKVNFHMFDVGAQRDERRKWIQCFNDVTAIIFVVDSSDYNRLQEALNDFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCSVDTENARRIFNDCRDIIQRMHLRQYELL,Homo sapiens,no,AVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLE,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
6,SabDab_nano,\,7JHG,No,ELECTRON MICROSCOPY,Cryo-EM structure of ATP-bound fully inactive AMPK in complex with Dorsomorphin (Compound C) and Fab-nanobody,VRAI,scFv,synthetic construct,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,73305.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
7,SabDab_nano,\,7KH0,No,ELECTRON MICROSCOPY,Cryo-EM structure of the human arginine vasopressin AVP-vasopressin receptor V2R-Gs signaling complex,VRAI,scFv,Lama glama,7.0,G,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,R,UniProt,P30518,\,GCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQDDYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,4.4955362e-10,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm
8,SabDab_nano,\,7KN6,No,X-RAY DIFFRACTION,Crystal structure of SARS-CoV-2 receptor binding domain complexed with nanobody VHH V and antibody Fab CC12.3,VRAI,scFv,Homo sapiens,3.0,C,H,NaN,NaN,21261.0,100.0,CC12.3 Fab heavy chain,4.0,D,L,NaN,NaN,101030.0,100.0,CC12.3 Fab light chain,1.0,A,A,UniProt,P0DTC2,\,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFSGHHHHHH,Severe acute respiratory syndrome coronavirus 2,no,QVQLVESGGGLIQPGGSLRLSCAASGFTVSSNYMSWVRQAPGKGLEWVSVIYSGGSTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARDFGDFYFDYWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPRTFGQGTKLEIK,GFTVSSN,YSGGS,DFGDFYFDY,RASQSVSSYLA,GASSRAT,QQYGSSPRT,Chothia,6.758231e-09,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm
9,SabDab_nano,\,7M74,No,ELECTRON MICROSCOPY,ATP-bound AMP-activated protein kinase,VRAI,scFv,Homo sapiens,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,621166.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
10,SabDab_nano,\,7O31,No,X-RAY DIFFRACTION,Crystal structure of the anti-PAS Fab 1.2 in complex with its epitope peptide and the anti-Kappa VHH domain,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,463058.0,100.0,anti-PAS Fab 1.2 chimeric heavy chain,1.0,A,L,NaN,NaN,463061.0,100.0,anti-PAS Fab 1.2 chimeric light chain,4.0,D,P,NaN,NaN,\,QAPASPAAPA,synthetic construct,no,EVQLVESGGGLVQPGGSLKLSCAASGFTFSSYGMSWVRQTPDKRLELVATINSNGGSTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRGGSIYDGYDYAMDYWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCRASQSVSTSSYSYMHWFQQKPGQPPKLLIKYASNLESGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCQHSWEIPLTFGAGTKLEIK,GFTFSSY,NSNGGS,GGSIYDGYDYAMDY,RASQSVSTSSYSYMH,YASNLES,QHSWEIPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
11,SabDab_nano,\,7Q6C,No,X-RAY DIFFRACTION,complement C6 FIM1-2 bound to CP010 antibody,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,404023.0,100.0,CP010 heavy chain,4.0,D,L,NaN,NaN,404025.0,100.0,CP010 light chain,1.0,A,A,UniProt,P13671,\,LKGHCQLGQKQSGSECICMSPEEDCSHHSEDLCVFDTDSNDYFTSPACKFLAEKCLNNQQLHFLHIGSCQDGRQLEWGLERTRLSSASTKKESCGYDTCYDWEKCSASTSKCVCLLPPQCFKGGNQLYCVKMGSSTSEKTLNICEVGTIRCANRKMEILHPGKCLA,Homo sapiens,no,EVQLVESDGGLVQPGGSLKLSCAASGFTFSDYYMAWVRQGPGKGLEWVATINYDGSSTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARPSTEALFAYWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCRSSQSLLNDVGNTYLYWYLQKPGQSPQLLIYLVSDLGSGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCMQASHAPYTFGQGTNLEIK,GFTFSDY,NYDGSS,PSTEALFAY,RSSQSLLNDVGNTYLY,LVSDLGS,MQASHAPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
12,SabDab_nano,\,7RG9,No,ELECTRON MICROSCOPY,cryo-EM of human Glucagon-like peptide 1 receptor GLP-1R in apo form,VRAI,scFv,Lama glama,5.0,E,N,NaN,NaN,283.0,100.0,nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P63092,\,MHHHHHHGSSGSELDQLRQEAEQLKNQIRDARKACADATLSQITNNIDPVGRIQMRTRRTLRGHLAKIYAMHWGTDSRLLVSASQDGKLIIWDSYTTNKVHAIPLRSSWVMTCAYAPSGNYVACGGLDNICSIYNLKTREGNVRVSRELAGHTGYLSCCRFLDDNQIVTSSGDTTCALWDIETGQQTTTFTGHTGDVMSLSLAPDTRLFVSGACDASAKLWDVREGMCRQTFTGHESDINAICFFPNGNAFATGSDDATCRLFDLRADQELMTYSHDNIICGITSVSFSKSGRLLLAGYDDFNCNVWDALKADRAGVLAGHDNRVSCLGVTDDGMAVATGSWDSFLKIWN/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQADYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
13,SabDab_nano,2022-04-03 00:00:00,7UL3,No,ELECTRON MICROSCOPY,"CryoEM Structure of Inactive H2R Bound to Famotidine, Nb6M, and NabFab",VRAI,scFv,synthetic construct,2.0,B,C,NaN,NaN,460880.0,100.0,Nanobody 6M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P25021,\,\,Homo sapiens,no,QRQLVESGGGLVQPGGSLRLSCAASGTIFRLYDMGWFRQAPGKEREGVASITSGGSTKYADSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCNAEYRTGIWEELLDGWGKGTPVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSSLITFGQGTKVEIK,GTIFRLYD,ITSGGST,NAEYRTGIWEELLDG,RASQSVSSAVA,SASSLYS,QQSSSSLIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
14,SabDab_nano,\,7WPD,No,ELECTRON MICROSCOPY,SARS-CoV-2 Omicron Variant S Trimer complexed with one JMB2002 Fab,VRAI,scFv,Mus musculus,2.0,D,X,NaN,NaN,18014.0,100.0,JMB2002 Fab heavy chain,3.0,E,Y,NaN,NaN,35543.0,100.0,JMB2002 Fab light chian,1.0,"A, B, C","A, B, C",UniProt,P0DTC2,\,MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHVISGTNGTKRFDNPVLPFNDGVYFASIEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLDHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPIIVREPEDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVADYSVLYNLAPFFTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGNIADYNYKLPDDFTGCVIAWNSNKLDSKVSGNYNYLYRLFRKSNLKPFERDISTEIYQAGNKPCNGVAGFNCYFPLRSYSFRPTYGVGHQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLKGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQGVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEYVNNSYECDIPIGAGICASYQTQTKSHGSASSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLKRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKYFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFKGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNHNAQALNTLVKQLSSKFGAISSVLNDIFSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQ,Severe acute respiratory syndrome coronavirus 2,no,QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGRIIPIFGTANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCASLASYSSGWEDVFDIWGQGTMVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKLLIYDASNLETGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCQQYDNLPLTFGGGTKVEIK,GGTFSSY,IPIFGT,LASYSSGWEDVFDI,RASQGISSWLA,DASNLET,QQYDNLPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
15,SabDab_nano,\,7WPF,No,ELECTRON MICROSCOPY,SARS-CoV-2 Omicron Variant S Trimer complexed with three JMB2002 Fab,VRAI,scFv,Mus musculus,2.0,"D, G, J","R, U, X",NaN,NaN,18014.0,100.0,JMB2002 Fab heavy chain,3.0,"E, H, K","S, V, Y",NaN,NaN,87724.0,100.0,JMB2002 Fab light chain,1.0,"A, B, C","A, B, C",UniProt,P0DTC2,\,MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHVISGTNGTKRFDNPVLPFNDGVYFASIEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLDHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPIIVREPEDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVADYSVLYNLAPFFTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGNIADYNYKLPDDFTGCVIAWNSNKLDSKVSGNYNYLYRLFRKSNLKPFERDISTEIYQAGNKPCNGVAGFNCYFPLRSYSFRPTYGVGHQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLKGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQGVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEYVNNSYECDIPIGAGICASYQTQTKSHGSASSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLKRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKYFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFKGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNHNAQALNTLVKQLSSKFGAISSVLNDIFSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQ,Severe acute respiratory syndrome coronavirus 2,no,QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGRIIPIFGTANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCASLASYSSGWEDVFDIWGQGTMVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKLLIYDASNLETGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCQQYDNLPLTFGGGTKVEIK,GGTFSSY,IPIFGT,LASYSSGWEDVFDI,RASQGISSWLA,DASNLET,QQYDNLPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
16,SabDab_nano,\,7WUJ,No,ELECTRON MICROSCOPY,Tethered peptide activation mechanism of adhesion GPCRs ADGRG2 and ADGRG4,VRAI,scFv,Lama glama,6.0,F,N,NaN,NaN,669.0,100.0,Nanobody-35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P63092,\,MHHHHHHLEVLFQGPGSSQSELDQLRQEAEQLKNQIRDARKACADATLSQITNNIDPVGRIQMRTRRTLRGHLAKIYAMHWGTDSRLLVSASQDGKLIIWDSYTTNKVHAIPLRSSWVMTCAYAPSGNYVACGGLDNICSIYNLKTREGNVRVSRELAGHTGYLSCCRFLDDNQIVTSSGDTTCALWDIETGQQTTTFTGHTGDVMSLSLAPDTRLFVSGACDASAKLWDVREGMCRQTFTGHESDINAICFFPNGNAFATGSDDATCRLFDLRADQELMTYSHDNIICGITSVSFSKSGRLLLAGYDDFNCNVWDALKADRAGVLAGHDNRVSCLGVTDDGMAVATGSWDSFLKIWN/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGADNSGKSTIVKQMRIYHVNGYSEEECKQYKAVVYSNTIQSIIAIIRAMGRLKIDFGDSARADDARQLFVLAGAAEEGFMTAELAGVIKRLWKDSGVQACFNRSREYQLNDSAAYYLNDLDRIAQPNYIPTQQDVLRTRVKTSGIFETKFQVDKVNFHMFDVGAQRDERRKWIQCFNDVTAIIFVVDSSDYNRLQEALNDFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCSVDTENARRIFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation

In [7]:
df_to_save[:2]

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation

In [8]:
'X'*3

'XXX'

In [9]:
df_to_save['heavy_with_X'] = df_to_save.apply(lambda x: x['Ab/Nano H_Chain AA'].replace(x['Ab/Nano_CDR H1'], 'X'*len(x['Ab/Nano_CDR H1'])).replace(x['Ab/Nano_CDR H2'], 'X'*len(x['Ab/Nano_CDR H2'])).replace(x['Ab/Nano_CDR H3'], 'X'*len(x['Ab/Nano_CDR H3'])), axis=1)
df_to_save['light_with_X'] = df_to_save.apply(lambda x: x['Ab/Nano L_Chain AA'].replace(x['Ab/Nano_CDR L1'], 'X'*len(x['Ab/Nano_CDR L1'])).replace(x['Ab/Nano_CDR L2'], 'X'*len(x['Ab/Nano_CDR L2'])).replace(x['Ab/Nano_CDR L3'], 'X'*len(x['Ab/Nano_CDR L3'])), axis=1)
df_to_save

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance,heavy_with_X,light_with_X
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK
2,SabDab_nano,\,5EOC,No,X-RAY DIFFRACTION,Crystal structure of Fab C2 in complex with a Cyclic variant of Hepatitis C Virus E2 epitope I,VRAI,scFv,Mus musculus,3.0,C,J,NaN,NaN,170146.0,100.0,Fab fragment (Heavy chain),2.0,"B, D","L, M",NaN,NaN,170143.0,100.0,Fab fragment (Light chain),4.0,"E, F","P, Q",UniProt,P27958,ala-cys-gln-leu-ile-asn-thr-asn-gly-ser-trp-his-ile-cys,ACQLINTNGSWHIC,Hepacivirus hominis,no,EVQLQQPGAELVRPGGSVKLSCKASGYSFTTYWMMWVKQRPGQGLEWIGMIQPSDSETRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARTGRGDAWLTYWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCRASKSVSTSGYSYMHWYQQKPGQPPRLLLYLGSNLESGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCQHIRELTRSFGGGTKLEIK,GYSFTTY,QPSDSE,TGRGDAWLTY,RASKSVSTSGYSYMH,LGSNLES,QHIRELTRS,Chothia,3.03E-08,"-10,25714745",NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,EVQLQQPGAELVRPGGSVKLSCKASXXXXXXXWMMWVKQRPGQGLEWIGMIXXXXXXTRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARXXXXXXXXXXWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCXXXXXXXXXXXXXXXWYQQKPGQPPRLLLYXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCXXXXXXXXXFGGGTKLEIK
3,SabDab_nano,2019-01-29 00:00:00,6QKD,No,X-RAY DIFFRACTION,CRYSTAL STRUCTURE OF vhh-based FAB-fragment of antibody BCD-085,VRAI,scFv,Lama glama,1.0,"A, B, C, D","H, I, J, K",NaN,NaN,1019893.0,100.0,FAB HEAVY CHAIN,2.0,"E, F, G, H","L, M, O, T",NaN,NaN,1019895.0,100.0,FAB LIGHT CHAIN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,QVQLVQSGGGLVQAGGSLRLSCAASGGTFATSPMGWLRQAPGKGTEFVAAISPSGGDRIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCAVRRRFDGTSYYTGDYDSWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYDASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYSYSPVTFGQGTKVEIK,GGTFATSP,ISPSGGDR,AVRRRFDGTSYYTGDYDS,RASQSVSSSYLA,DASSRAT,QQYSYSPVT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QVQLVQSGGGLVQAGGSLRLSCAASXXXXXXXXMGWLRQAPGKGTEFVAAXXXXXXXXIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCXXXXXXXXXXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKVEIK
4,SabDab_nano,2020-06-21 00:00:00,6ZH9,No,X-RAY DIFFRACTION,Ternary complex CR3022 H11-H4 and RBD (SARS-CoV-2),VRAI,scFv,Homo sapiens,1.0,A,HHH,NaN,NaN,94476.0,100.0,CR3022 heavy,2.0,B,LLL,NaN,NaN,2814.0,100.0,CR3022 Light chain,1.0,A,HHH,NaN,NaN,unknown,ITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPK,Homo sapiens,no,QVQLVESGGGLMQAGGSLRLSCAVSGRTFSTAAMGWFRQAPGKEREFVAAIRWSGGSAYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCAQTHYVSYLLSDYATWPYDYWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCKSSQSVLYSSINKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTPYTFGQGTKVEIK,GRTFSTAA,IRWSGGSA,AQTHYVSYLLSDYATWPYDY,KSSQSVLYSSINKNYLA,WASTRES,QQYYSTPYT,Chothia,6.594088e-06,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLMQAGGSLRLSCAVSXXXXXXXXMGWFRQAPGKEREFVAAXXXXXXXXYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCXXXXXXXXXXXXXXXXXXXXWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCXXXXXXXXXXXXXXXXXWYQQKPGQPPKLLIYXXXXXXXGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCXXXXXXXXXFGQGTKVEIK
5,SabDab_nano,\,7F4H,No,ELECTRON MICROSCOPY,"Cryo-EM structure of afamelanotide-bound melanocortin-1 receptor in complex with Gs protein, Nb35 and scFv16",VRAI,scFv,synthetic construct,3.0,C,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,G,UniProt,P59768,\,MASNNTASIAQARKLVEQLKMEANIDRIKVSKAAADLMAYCEAHAKEDPLLTPVPASENPFREKKFFCAIL/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGADNSGKSTIVKQMRIYHVNGYSEEECKQYKAVVYSNTIQSIIAIIRAMGRLKIDFGDSARADDARQLFVLAGAAEEGFMTAELAGVIKRLWKDSGVQACFNRSREYQLNDSAAYYLNDLDRIAQPNYIPTQQDVLRTRVKTSGIFETKFQVDKVNFHMFDVGAQRDERRKWIQCFNDVTAIIFVVDSSDYNRLQEALNDFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCSVDTENARRIFNDCRDIIQRMHLRQYELL,Homo sapiens,no,AVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLE,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,AVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLE
6,SabDab_nano,\,7JHG,No,ELECTRON MICROSCOPY,Cryo-EM structure of ATP-bound fully inactive AMPK in complex with Dorsomorphin (Compound C) and Fab-nanobody,VRAI,scFv,synthetic construct,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,73305.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK
7,SabDab_nano,\,7KH0,No,ELECTRON MICROSCOPY,Cryo-EM structure of the human arginine vasopressin AVP-vasopressin receptor V2R-Gs signaling complex,VRAI,scFv,Lama glama,7.0,G,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,R,UniProt,P30518,\,GCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQDDYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,4.4955362e-10,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK
8,SabDab_nano,\,7KN6,No,X-RAY DIFFRACTION,Crystal structure of SARS-CoV-2 receptor binding domain complexed with nanobody VHH V and antibody Fab CC12.3,VRAI,scFv,Homo sapiens,3.0,C,H,NaN,NaN,21261.0,100.0,CC12.3 Fab heavy chain,4.0,D,L,NaN,NaN,101030.0,100.0,CC12.3 Fab light chain,1.0,A,A,UniProt,P0DTC2,\,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFSGHHHHHH,Severe acute respiratory syndrome coronavirus 2,no,QVQLVESGGGLIQPGGSLRLSCAASGFTVSSNYMSWVRQAPGKGLEWVSVIYSGGSTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARDFGDFYFDYWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPRTFGQGTKLEIK,GFTVSSN,YSGGS,DFGDFYFDY,RASQSVSSYLA,GASSRAT,QQYGSSPRT,Chothia,6.758231e-09,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLIQPGGSLRLSCAASXXXXXXXYMSWVRQAPGKGLEWVSVIXXXXXTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKLEIK
9,SabDab_nano,\,7M74,No,ELECTRON MICROSCOPY,ATP-bound AMP-activated protein kinase,VRAI,scFv,Homo sapiens,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,621166.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK
10,SabDab_nano,\,7O31,No,X-RAY DIFFRACTION,Crystal structure of the anti-PAS Fab 1.2 in complex with its epitope peptide and the anti-Kappa VHH domain,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,463058.0,100.0,anti-PAS Fab 1.2 chimeric heavy chain,1.0,A,L,NaN,NaN,463061.0,100.0,anti-PAS Fab 1.2 chimeric light chain,4.0,D,P,NaN,NaN,\,QAPASPAAPA,synthetic construct,no,EVQLVESGGGLVQPGGSLKLSCAASGFTFSSYGMSWVRQTPDKRLELVATINSNGGSTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRGGSIYDGYDYAMDYWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCRASQSVSTSSYSYMHWFQQKPGQPPKLLIKYASNLESGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCQHSWEIPLTFGAGTKLEIK,GFTFSSY,NSNGGS,GGSIYDGYDYAMDY,RASQSVSTSSYSYMH,YASNLES,QHSWEIPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLKLSCAASXXXXXXXGMSWVRQTPDKRLELVATIXXXXXXTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRXXXXXXXXXXXXXXWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCXXXXXXXXXXXXXXXWFQQKPGQPPKLLIKXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCXXXXXXXXXFGAGTKLEIK
11,SabDab_nano,\,7Q6C,No,X-RAY DIFFRACTION,complement C6 FIM1-2 bound to CP010 antibody,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,404023.0,100.0,CP010 heavy chain,4.0,D,L,NaN,NaN,404025.0,100.0,CP010 light chain,1.0,A,A,UniProt,P13671,\,LKGHCQLGQKQSGSECICMSPEEDCSHHSEDLCVFDTDSNDYFTSPACKFLAEKCLNNQQLHFLHIGSCQDGRQLEWGLERTRLSSASTKKESCGYDTCYDWEKCSASTSKCVCLLPPQCFKGGNQLYCVKMGSSTSEKTLNICEVGTIRCANRKMEILHPGKCLA,Homo sapiens,no,EVQLVESDGGLVQPGGSLKLSCAASGFTFSDYYMAWVRQGPGKGLEWVATINYDGSSTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARPSTEALFAYWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCRSSQSLLNDVGNTYLYWYLQKPGQSPQLLIYLVSDLGSGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCMQASHAPYTFGQGTNLEIK,GFTFSDY,NYDGSS,PSTEALFAY,RSSQSLLNDVGNTYLY,LVSDLGS,MQASHAPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESDGGLVQPGGSLKLSCAASXXXXXXXYMAWVRQGPGKGLEWVATIXXXXXXTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARXXXXXXXXXWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCXXXXXXXXXXXXXXXXWYLQKPGQSPQLLIYXXXXXXXGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCXXXXXXXXXFGQGTNLEIK
12,SabDab_nano,\,7RG9,No,ELECTRON MICROSCOPY,cryo-EM of human Glucagon-like peptide 1 receptor GLP-1R in apo form,VRAI,scFv,Lama glama,5.0,E,N,NaN,NaN,283.0,100.0,nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P63092,\,MHHHHHHGSSGSELDQLRQEAEQLKNQIRDARKACADATLSQITNNIDPVGRIQMRTRRTLRGHLAKIYAMHWGTDSRLLVSASQDGKLIIWDSYTTNKVHAIPLRSSWVMTCAYAPSGNYVACGGLDNICSIYNLKTREGNVRVSRELAGHTGYLSCCRFLDDNQIVTSSGDTTCALWDIETGQQTTTFTGHTGDVMSLSLAPDTRLFVSGACDASAKLWDVREGMCRQTFTGHESDINAICFFPNGNAFATGSDDATCRLFDLRADQELMTYSHDNIICGITSVSFSKSGRLLLAGYDDFNCNVWDALKADRAGVLAGHDNRVSCLGVTDDGMAVATGSWDSFLKIWN/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQADYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK
13,SabDab_nano,2022-04-03 00:00:00,7UL3,No,ELECTRON MICROSCOPY,"CryoEM Structure of Inactive H2R Bound to Famotidine, Nb6M, and NabFab",VRAI,scFv,synthetic construct,2.0,B,C,NaN,NaN,460880.0,100.0,Nanobody 6M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P25021,\,\,Homo sapiens,no,QRQLVESGGGLVQPGGSLRLSCAASGTIFRLYDMGWFRQAPGKEREGVASITSGGSTKYADSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCNAEYRTGIWEELLDGWGKGTPVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSSLITFGQGTKVEIK,GTIFRLYD,ITSGGST,NAEYRTGIWEELLDG,RASQSVSSAVA,SASSLYS,QQSSSSLIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QRQLVESGGGLVQPGGSLRLSCAASXXXXXXXXMGWFRQAPGKEREGVASXXXXXXXKYADSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCXXXXXXXXXXXXXXXWGKGTPVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK
14,SabDab_nano,\,7WPD,No,ELECTRON MICROSCOPY,SARS-CoV-2 Omicron Variant S Trimer complexed with one JMB2002 Fab,VRAI,scFv,Mus musculus,2.0,D,X,NaN,NaN,18014.0,100.0,JMB2002 Fab heavy chain,3.0,E,Y,NaN,NaN,35543.0,100.0,JMB2002 Fab light chian,1.0,"A, B, C","A, B, C",UniProt,P0DTC2,\,MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHVISGTNGTKRFDNPVLPFNDGVYFASIEKSNIIRGWIFGTTLDSKTQSLLIVNNATNVVIKVCEFQFCNDPFLDHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPIIVREPEDLPQGFSALEPLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLCPFDEVFNATRFASVYAWNRKRISNCVADYSVLYNLAPFFTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGNIADYNYKLPDDFTGCVIAWNSNKLDSKVSGNYNYLYRLFRKSNLKPFERDISTEIYQAGNKPCNGVAGFNCYFPLRSYSFRPTYGVGHQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLKGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQGVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEYVNNSYECDIPIGAGICASYQTQTKSHGSASSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLKRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKYFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFKGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNHNAQALNTLVKQLSSKFGAISSVLNDIFSRLDPPEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQ,Severe acute respiratory syndrome coronavirus 2,no,QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYAISWVRQAPGQGLEWMGRIIPIFGTANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCASLASYSSGWEDVFDIWGQGTMVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKLLIYDASNLETGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCQQYDNLPLTFGGGTKVEIK,GGTFSSY,IPIFGT,LASYSSGWEDVFDI,RASQGISSWLA,DASNLET,QQYDNLPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QVQLVQSGAEVKKPGSSVKVSCKASXXXXXXXAISWVRQAPGQGLEWMGRIXXXXXXANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCASXXXXXXXXXXXXXXWGQGTMVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSGSGTDFTFTISSLQPEDIATYYCXXXXXXXXXFGGGTKVEIK

In [10]:
len([i for i in df_to_save['heavy_with_X'].iloc[0].split('X') if not i == ''])

4

In [11]:
df_to_save['is_ok'] = df_to_save.apply(lambda x: len([i for i in x['heavy_with_X'].split('X') if not i == '']) == 4 and len([i for i in x['light_with_X'].split('X') if not i == '']) == 4, axis=1)
df_to_save['is_ok'].value_counts()

is_ok
True    26
Name: count, dtype: int64

In [12]:
df_to_save['id'] = range(1, len(df_to_save) + 1)
df_to_save['id'] = df_to_save.apply(lambda x: f"{x['PDB_ID']}-{x['id']}_{len(x['Ab/Nano H_Chain AA']) + 1}_{len(x['Ab/Nano H_Chain AA']) + 1 + 14}", axis=1)
df_to_save

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance,heavy_with_X,light_with_X,is_ok,id
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL,True,3MLT-1_125_139
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK,True,3NID-2_120_134
2,SabDab_nano,\,5EOC,No,X-RAY DIFFRACTION,Crystal structure of Fab C2 in complex with a Cyclic variant of Hepatitis C Virus E2 epitope I,VRAI,scFv,Mus musculus,3.0,C,J,NaN,NaN,170146.0,100.0,Fab fragment (Heavy chain),2.0,"B, D","L, M",NaN,NaN,170143.0,100.0,Fab fragment (Light chain),4.0,"E, F","P, Q",UniProt,P27958,ala-cys-gln-leu-ile-asn-thr-asn-gly-ser-trp-his-ile-cys,ACQLINTNGSWHIC,Hepacivirus hominis,no,EVQLQQPGAELVRPGGSVKLSCKASGYSFTTYWMMWVKQRPGQGLEWIGMIQPSDSETRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARTGRGDAWLTYWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCRASKSVSTSGYSYMHWYQQKPGQPPRLLLYLGSNLESGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCQHIRELTRSFGGGTKLEIK,GYSFTTY,QPSDSE,TGRGDAWLTY,RASKSVSTSGYSYMH,LGSNLES,QHIRELTRS,Chothia,3.03E-08,"-10,25714745",NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,EVQLQQPGAELVRPGGSVKLSCKASXXXXXXXWMMWVKQRPGQGLEWIGMIXXXXXXTRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARXXXXXXXXXXWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCXXXXXXXXXXXXXXXWYQQKPGQPPRLLLYXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCXXXXXXXXXFGGGTKLEIK,True,5EOC-3_120_134
3,SabDab_nano,2019-01-29 00:00:00,6QKD,No,X-RAY DIFFRACTION,CRYSTAL STRUCTURE OF vhh-based FAB-fragment of antibody BCD-085,VRAI,scFv,Lama glama,1.0,"A, B, C, D","H, I, J, K",NaN,NaN,1019893.0,100.0,FAB HEAVY CHAIN,2.0,"E, F, G, H","L, M, O, T",NaN,NaN,1019895.0,100.0,FAB LIGHT CHAIN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,QVQLVQSGGGLVQAGGSLRLSCAASGGTFATSPMGWLRQAPGKGTEFVAAISPSGGDRIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCAVRRRFDGTSYYTGDYDSWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYDASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYSYSPVTFGQGTKVEIK,GGTFATSP,ISPSGGDR,AVRRRFDGTSYYTGDYDS,RASQSVSSSYLA,DASSRAT,QQYSYSPVT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QVQLVQSGGGLVQAGGSLRLSCAASXXXXXXXXMGWLRQAPGKGTEFVAAXXXXXXXXIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCXXXXXXXXXXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKVEIK,True,6QKD-4_126_140
4,SabDab_nano,2020-06-21 00:00:00,6ZH9,No,X-RAY DIFFRACTION,Ternary complex CR3022 H11-H4 and RBD (SARS-CoV-2),VRAI,scFv,Homo sapiens,1.0,A,HHH,NaN,NaN,94476.0,100.0,CR3022 heavy,2.0,B,LLL,NaN,NaN,2814.0,100.0,CR3022 Light chain,1.0,A,HHH,NaN,NaN,unknown,ITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPK,Homo sapiens,no,QVQLVESGGGLMQAGGSLRLSCAVSGRTFSTAAMGWFRQAPGKEREFVAAIRWSGGSAYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCAQTHYVSYLLSDYATWPYDYWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCKSSQSVLYSSINKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTPYTFGQGTKVEIK,GRTFSTAA,IRWSGGSA,AQTHYVSYLLSDYATWPYDY,KSSQSVLYSSINKNYLA,WASTRES,QQYYSTPYT,Chothia,6.594088e-06,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLMQAGGSLRLSCAVSXXXXXXXXMGWFRQAPGKEREFVAAXXXXXXXXYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCXXXXXXXXXXXXXXXXXXXXWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCXXXXXXXXXXXXXXXXXWYQQKPGQPPKLLIYXXXXXXXGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCXXXXXXXXXFGQGTKVEIK,True,6ZH9-5_128_142
5,SabDab_nano,\,7F4H,No,ELECTRON MICROSCOPY,"Cryo-EM structure of afamelanotide-bound melanocortin-1 receptor in complex with Gs protein, Nb35 and scFv16",VRAI,scFv,synthetic construct,3.0,C,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,G,UniProt,P59768,\,MASNNTASIAQARKLVEQLKMEANIDRIKVSKAAADLMAYCEAHAKEDPLLTPVPASENPFREKKFFCAIL/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGADNSGKSTIVKQMRIYHVNGYSEEECKQYKAVVYSNTIQSIIAIIRAMGRLKIDFGDSARADDARQLFVLAGAAEEGFMTAELAGVIKRLWKDSGVQACFNRSREYQLNDSAAYYLNDLDRIAQPNYIPTQQDVLRTRVKTSGIFETKFQVDKVNFHMFDVGAQRDERRKWIQCFNDVTAIIFVVDSSDYNRLQEALNDFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCSVDTENARRIFNDCRDIIQRMHLRQYELL,Homo sapiens,no,AVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLE,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,AVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLE,True,7F4H-6_121_135
6,SabDab_nano,\,7JHG,No,ELECTRON MICROSCOPY,Cryo-EM structure of ATP-bound fully inactive AMPK in complex with Dorsomorphin (Compound C) and Fab-nanobody,VRAI,scFv,synthetic construct,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,73305.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK,True,7JHG-7_127_141
7,SabDab_nano,\,7KH0,No,ELECTRON MICROSCOPY,Cryo-EM structure of the human arginine vasopressin AVP-vasopressin receptor V2R-Gs signaling complex,VRAI,scFv,Lama glama,7.0,G,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,R,UniProt,P30518,\,GCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQDDYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,4.4955362e-10,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK,True,7KH0-8_122_136
8,SabDab_nano,\,7KN6,No,X-RAY DIFFRACTION,Crystal structure of SARS-CoV-2 receptor binding domain complexed with nanobody VHH V and antibody Fab CC12.3,VRAI,scFv,Homo sapiens,3.0,C,H,NaN,NaN,21261.0,100.0,CC12.3 Fab heavy chain,4.0,D,L,NaN,NaN,101030.0,100.0,CC12.3 Fab light chain,1.0,A,A,UniProt,P0DTC2,\,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFSGHHHHHH,Severe acute respiratory syndrome coronavirus 2,no,QVQLVESGGGLIQPGGSLRLSCAASGFTVSSNYMSWVRQAPGKGLEWVSVIYSGGSTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARDFGDFYFDYWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPRTFGQGTKLEIK,GFTVSSN,YSGGS,DFGDFYFDY,RASQSVSSYLA,GASSRAT,QQYGSSPRT,Chothia,6.758231e-09,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLIQPGGSLRLSCAASXXXXXXXYMSWVRQAPGKGLEWVSVIXXXXXTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKLEIK,True,7KN6-9_118_132
9,SabDab_nano,\,7M74,No,ELECTRON MICROSCOPY,ATP-bound AMP-activated protein kinase,VRAI,scFv,Homo sapiens,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,621166.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK,True,7M74-10_127_141
10,SabDab_nano,\,7O31,No,X-RAY DIFFRACTION,Crystal structure of the anti-PAS Fab 1.2 in complex with its epitope peptide and the anti-Kappa VHH domain,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,463058.0,100.0,anti-PAS Fab 1.2 chimeric heavy chain,1.0,A,L,NaN,NaN,463061.0,100.0,anti-PAS Fab 1.2 chimeric light chain,4.0,D,P,NaN,NaN,\,QAPASPAAPA,synthetic construct,no,EVQLVESGGGLVQPGGSLKLSCAASGFTFSSYGMSWVRQTPDKRLELVATINSNGGSTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRGGSIYDGYDYAMDYWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCRASQSVSTSSYSYMHWFQQKPGQPPKLLIKYASNLESGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCQHSWEIPLTFGAGTKLEIK,GFTFSSY,NSNGGS,GGSIYDGYDYAMDY,RASQSVSTSSYSYMH,YASNLES,QHSWEIPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLKLSCAASXXXXXXXGMSWVRQTPDKRLELVATIXXXXXXTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRXXXXXXXXXXXXXXWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCXXXXXXXXXXXXXXXWFQQKPGQPPKLLIKXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCXXXXXXXXXFGAGTKLEIK,True,7O31-11_124_138
11,SabDab_nano,\,7Q6C,No,X-RAY DIFFRACTION,complement C6 FIM1-2 bound to CP010 antibody,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,404023.0,100.0,CP010 heavy chain,4.0,D,L,NaN,NaN,404025.0,100.0,CP010 light chain,1.0,A,A,UniProt,P13671,\,LKGHCQLGQKQSGSECICMSPEEDCSHHSEDLCVFDTDSNDYFTSPACKFLAEKCLNNQQLHFLHIGSCQDGRQLEWGLERTRLSSASTKKESCGYDTCYDWEKCSASTSKCVCLLPPQCFKGGNQLYCVKMGSSTSEKTLNICEVGTIRCANRKMEILHPGKCLA,Homo sapiens,no,EVQLVESDGGLVQPGGSLKLSCAASGFTFSDYYMAWVRQGPGKGLEWVATINYDGSSTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARPSTEALFAYWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCRSSQSLLNDVGNTYLYWYLQKPGQSPQLLIYLVSDLGSGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCMQASHAPYTFGQGTNLEIK,GFTFSDY,NYDGSS,PSTEALFAY,RSSQSLLNDVGNTYLY,LVSDLGS,MQASHAPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESDGGLVQPGGSLKLSCAASXXXXXXXYMAWVRQGPGKGLEWVATIXXXXXXTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARXXXXXXXXXWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCXXXXXXXXXXXXXXXXWYLQKPGQSPQLLIYXXXXXXXGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCXXXXXXXXXFGQGTNLEIK,True,7Q6C-12_119_133
12,SabDab_nano,\,7RG9,No,ELECTRON MICROSCOPY,cryo-EM of human Glucagon-like peptide 1 receptor GLP-1R in apo form,VRAI,scFv,Lama glama,5.0,E,N,NaN,NaN,283.0,100.0,nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P63092,\,MHHHHHHGSSGSELDQLRQEAEQLKNQIRDARKACADATLSQITNNIDPVGRIQMRTRRTLRGHLAKIYAMHWGTDSRLLVSASQDGKLIIWDSYTTNKVHAIPLRSSWVMTCAYAPSGNYVACGGLDNICSIYNLKTREGNVRVSRELAGHTGYLSCCRFLDDNQIVTSSGDTTCALWDIETGQQTTTFTGHTGDVMSLSLAPDTRLFVSGACDASAKLWDVREGMCRQTFTGHESDINAICFFPNGNAFATGSDDATCRLFDLRADQELMTYSHDNIICGITSVSFSKSGRLLLAGYDDFNCNVWDALKADRAGVLAGHDNRVSCLGVTDDGMAVATGSWDSFLKIWN/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQADYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSS,DIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK,True,7RG9-13_122_136
13,SabDab_nano,2022-04-03 00:00:00,7UL3,No,ELECTRON MICROSCOPY,"CryoEM Structure of Inactive H2R Bound to Famotidine, Nb6M, and NabFab",VRAI,scFv,synthetic construct,2.0,B,C,NaN,NaN,460880.0,100.0,Nanobody 6M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,A,UniProt,P25021,\,\,Homo sapiens,no,QRQLVESGGGLVQPGGSLRLSCAASGTIFRLYDMGWFRQAPGKEREGVASITSGGSTKYADSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCNAEYRTGIWEELLDGWGKGTPVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSSLITFGQGTKVEIK,GTIFRLYD,ITSGGST,NAEYRTGIWEELLDG,RASQSVSSAVA,SASSLYS,QQSSSSLIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QRQLVESGGGLVQPGGSLRLSCAASXXXXXXXXMGWFRQAPGKEREGVASXXXXXXXKYADSVKGRFTISRDNAKNTVYLQMNSLEPEDTAVYYCXXXXXXXXXXXXXXXWGKGTPVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK,True,7UL3-14_122_136

In [13]:
linker = 'GGGGS'*3 # Use a G4S linker repeated 3 times
df_to_save['seq_with_linker'] = df_to_save.apply(lambda x: f"{x['heavy_with_X']}{linker}{x['light_with_X']}", axis=1)
df_to_save

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance,heavy_with_X,light_with_X,is_ok,id,seq_with_linker
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL,True,3MLT-1_125_139,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSSGGGGSGGGGSGGGGSYDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK,True,3NID-2_120_134,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSSGGGGSGGGGSGGGGSDILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK
2,SabDab_nano,\,5EOC,No,X-RAY DIFFRACTION,Crystal structure of Fab C2 in complex with a Cyclic variant of Hepatitis C Virus E2 epitope I,VRAI,scFv,Mus musculus,3.0,C,J,NaN,NaN,170146.0,100.0,Fab fragment (Heavy chain),2.0,"B, D","L, M",NaN,NaN,170143.0,100.0,Fab fragment (Light chain),4.0,"E, F","P, Q",UniProt,P27958,ala-cys-gln-leu-ile-asn-thr-asn-gly-ser-trp-his-ile-cys,ACQLINTNGSWHIC,Hepacivirus hominis,no,EVQLQQPGAELVRPGGSVKLSCKASGYSFTTYWMMWVKQRPGQGLEWIGMIQPSDSETRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARTGRGDAWLTYWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCRASKSVSTSGYSYMHWYQQKPGQPPRLLLYLGSNLESGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCQHIRELTRSFGGGTKLEIK,GYSFTTY,QPSDSE,TGRGDAWLTY,RASKSVSTSGYSYMH,LGSNLES,QHIRELTRS,Chothia,3.03E-08,"-10,25714745",NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,EVQLQQPGAELVRPGGSVKLSCKASXXXXXXXWMMWVKQRPGQGLEWIGMIXXXXXXTRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARXXXXXXXXXXWGQGTSVTVSS,NIVLTQSPVSLAVSLGQRATISCXXXXXXXXXXXXXXXWYQQKPGQPPRLLLYXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCXXXXXXXXXFGGGTKLEIK,True,5EOC-3_120_134,EVQLQQPGAELVRPGGSVKLSCKASXXXXXXXWMMWVKQRPGQGLEWIGMIXXXXXXTRLNQKFKDKATLTLDRSSSTVYMQLSSPTSDDSAVYYCARXXXXXXXXXXWGQGTSVTVSSGGGGSGGGGSGGGGSNIVLTQSPVSLAVSLGQRATISCXXXXXXXXXXXXXXXWYQQKPGQPPRLLLYXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDAATYYCXXXXXXXXXFGGGTKLEIK
3,SabDab_nano,2019-01-29 00:00:00,6QKD,No,X-RAY DIFFRACTION,CRYSTAL STRUCTURE OF vhh-based FAB-fragment of antibody BCD-085,VRAI,scFv,Lama glama,1.0,"A, B, C, D","H, I, J, K",NaN,NaN,1019893.0,100.0,FAB HEAVY CHAIN,2.0,"E, F, G, H","L, M, O, T",NaN,NaN,1019895.0,100.0,FAB LIGHT CHAIN,NaN,NaN,NaN,NaN,NaN,\,\,unknown,no,QVQLVQSGGGLVQAGGSLRLSCAASGGTFATSPMGWLRQAPGKGTEFVAAISPSGGDRIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCAVRRRFDGTSYYTGDYDSWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYDASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYSYSPVTFGQGTKVEIK,GGTFATSP,ISPSGGDR,AVRRRFDGTSYYTGDYDS,RASQSVSSSYLA,DASSRAT,QQYSYSPVT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,QVQLVQSGGGLVQAGGSLRLSCAASXXXXXXXXMGWLRQAPGKGTEFVAAXXXXXXXXIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCXXXXXXXXXXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKVEIK,True,6QKD-4_126_140,QVQLVQSGGGLVQAGGSLRLSCAASXXXXXXXXMGWLRQAPGKGTEFVAAXXXXXXXXIYADSVKGRFTISRDNAGYFIYLQMNSLKPEDTAVYYCXXXXXXXXXXXXXXXXXXWGQGTLVTVSSGGGGSGGGGSGGGGSEIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKVEIK
4,SabDab_nano,2020-06-21 00:00:00,6ZH9,No,X-RAY DIFFRACTION,Ternary complex CR3022 H11-H4 and RBD (SARS-CoV-2),VRAI,scFv,Homo sapiens,1.0,A,HHH,NaN,NaN,94476.0,100.0,CR3022 heavy,2.0,B,LLL,NaN,NaN,2814.0,100.0,CR3022 Light chain,1.0,A,HHH,NaN,NaN,unknown,ITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPK,Homo sapiens,no,QVQLVESGGGLMQAGGSLRLSCAVSGRTFSTAAMGWFRQAPGKEREFVAAIRWSGGSAYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCAQTHYVSYLLSDYATWPYDYWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCKSSQSVLYSSINKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTPYTFGQGTKVEIK,GRTFSTAA,IRWSGGSA,AQTHYVSYLLSDYATWPYDY,KSSQSVLYSSINKNYLA,WASTRES,QQYYSTPYT,Chothia,6.594088e-06,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLMQAGGSLRLSCAVSXXXXXXXXMGWFRQAPGKEREFVAAXXXXXXXXYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCXXXXXXXXXXXXXXXXXXXXWGQGTQVTVSS,DIQLTQSPDSLAVSLGERATINCXXXXXXXXXXXXXXXXXWYQQKPGQPPKLLIYXXXXXXXGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCXXXXXXXXXFGQGTKVEIK,True,6ZH9-5_128_142,QVQLVESGGGLMQAGGSLRLSCAVSXXXXXXXXMGWFRQAPGKEREFVAAXXXXXXXXYYADSVKGRFTISRDKAKNTVYLQMNSLKYEDTAVYYCXXXXXXXXXXXXXXXXXXXXWGQGTQVTVSSGGGGSGGGGSGGGGSDIQLTQSPDSLAVSLGERATINCXXXXXXXXXXXXXXXXXWYQQKPGQPPKLLIYXXXXXXXGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCXXXXXXXXXFGQGTKVEIK
5,SabDab_nano,\,7F4H,No,ELECTRON MICROSCOPY,"Cryo-EM structure of afamelanotide-bound melanocortin-1 receptor in complex with Gs protein, Nb35 and scFv16",VRAI,scFv,synthetic construct,3.0,C,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,G,UniProt,P59768,\,MASNNTASIAQARKLVEQLKMEANIDRIKVSKAAADLMAYCEAHAKEDPLLTPVPASENPFREKKFFCAIL/MGCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGADNSGKSTIVKQMRIYHVNGYSEEECKQYKAVVYSNTIQSIIAIIRAMGRLKIDFGDSARADDARQLFVLAGAAEEGFMTAELAGVIKRLWKDSGVQACFNRSREYQLNDSAAYYLNDLDRIAQPNYIPTQQDVLRTRVKTSGIFETKFQVDKVNFHMFDVGAQRDERRKWIQCFNDVTAIIFVVDSSDYNRLQEALNDFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCSVDTENARRIFNDCRDIIQRMHLRQYELL,Homo sapiens,no,AVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLE,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,AVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVS,DIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLE,True,7F4H-6_121_135,AVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSGGGGSGGGGSGGGGSDIVMTQATSSVPVTPGESVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLE
6,SabDab_nano,\,7JHG,No,ELECTRON MICROSCOPY,Cryo-EM structure of ATP-bound fully inactive AMPK in complex with Dorsomorphin (Compound C) and Fab-nanobody,VRAI,scFv,synthetic construct,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,73305.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,DIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK,True,7JHG-7_127_141,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSSGGGGSGGGGSGGGGSDIQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK
7,SabDab_nano,\,7KH0,No,ELECTRON MICROSCOPY,Cryo-EM structure of the human arginine vasopressin AVP-vasopressin receptor V2R-Gs signaling complex,VRAI,scFv,Lama glama,7.0,G,N,NaN,NaN,283.0,100.0,Nanobody 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,A,R,UniProt,P30518,\,GCTLSAEDKAAVERSKMIEKQLQKDKQVYRATHRLLLLGAGESGKSTIVKQMRILHVNGFNGDSEKATKVQDIKNNLKEAIETIVAAMSNLVPPVELANPENQFRVDYILSVMNVPDFDFPPEFYEHAKALWEDEGVRACYERSNEYQLIDCAQYFLDKIDVIKQDDYVPSDQDLLRCRVLTSGIFETKFQVDKVNFHMFDVGGQRDERRKWIQCFNDVTAIIFVVASSSYNMVIREDNQTNRLQEALNLFKSIWNNRWLRTISVILFLNKQDLLAEKVLAGKSKIEDYFPEFARYTTPEDATPEPGEDPRVTRAKYFIRDEFLRISTASGDGRHYCYPHFTCAVDTENIRRVFNDCRDIIQRMHLRQYELL,Homo sapiens,no,DVQLVESGGGLVQPGGSRKLSCSASGFAFSSFGMHWVRQAPEKGLEWVAYISSGSGTIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRSIYYYGSSPFDFWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCRSSKSLLHSNGNTYLYWFLQRPGQSPQLLIYRMSNLASGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCMQHLEYPLTFGAGTKLELK,GFAFSSF,SSGSGT,SIYYYGSSPFDF,RSSKSLLHSNGNTYLY,RMSNLAS,MQHLEYPLT,Chothia,4.4955362e-10,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSS,DIVMTQATSSVPVTPGLSVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK,True,7KH0-8_122_136,DVQLVESGGGLVQPGGSRKLSCSASXXXXXXXGMHWVRQAPEKGLEWVAYIXXXXXXIYYADTVKGRFTISRDDPKNTLFLQMTSLRSEDTAMYYCVRXXXXXXXXXXXXWGQGTTLTVSSGGGGSGGGGSGGGGSDIVMTQATSSVPVTPGLSVSISCXXXXXXXXXXXXXXXXWFLQRPGQSPQLLIYXXXXXXXGVPDRFSGSGSGTAFTLTISRLEAEDVGVYYCXXXXXXXXXFGAGTKLELK
8,SabDab_nano,\,7KN6,No,X-RAY DIFFRACTION,Crystal structure of SARS-CoV-2 receptor binding domain complexed with nanobody VHH V and antibody Fab CC12.3,VRAI,scFv,Homo sapiens,3.0,C,H,NaN,NaN,21261.0,100.0,CC12.3 Fab heavy chain,4.0,D,L,NaN,NaN,101030.0,100.0,CC12.3 Fab light chain,1.0,A,A,UniProt,P0DTC2,\,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFSGHHHHHH,Severe acute respiratory syndrome coronavirus 2,no,QVQLVESGGGLIQPGGSLRLSCAASGFTVSSNYMSWVRQAPGKGLEWVSVIYSGGSTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARDFGDFYFDYWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPRTFGQGTKLEIK,GFTVSSN,YSGGS,DFGDFYFDY,RASQSVSSYLA,GASSRAT,QQYGSSPRT,Chothia,6.758231e-09,NaN,NaN,\,real,SabDab_nano|PDB|schema_harmonisation|affinity_unit_norm,QVQLVESGGGLIQPGGSLRLSCAASXXXXXXXYMSWVRQAPGKGLEWVSVIXXXXXTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARXXXXXXXXXWGQGTLVTVSS,EIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKLEIK,True,7KN6-9_118_132,QVQLVESGGGLIQPGGSLRLSCAASXXXXXXXYMSWVRQAPGKGLEWVSVIXXXXXTFYADSVKGRFTISRDNSKSTLYLQMNSLRVEDTAVYYCARXXXXXXXXXWGQGTLVTVSSGGGGSGGGGSGGGGSEIVLTQSPGTLSLSPGERATLSCXXXXXXXXXXXWYQQKPGQAPRLLIYXXXXXXXGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCXXXXXXXXXFGQGTKLEIK
9,SabDab_nano,\,7M74,No,ELECTRON MICROSCOPY,ATP-bound AMP-activated protein kinase,VRAI,scFv,Homo sapiens,6.0,F,H,NaN,NaN,38684.0,100.0,Fab heavy chain,5.0,E,L,NaN,NaN,621166.0,100.0,Fab light chain,1.0,A,A,UniProt,Q13131,\,VKIGHYILGDTLGVGTFGKVKVGKHELTGHKVAVKILNRQKIRSLDVVGKIRREIQNLKLFRHPHIIKLYQVISTPSDIFMVMEYVSGGELFDYICKNGRLDEKESRRLFQQILSGVDYCHRHMVVHRDLKPENVLLDAHMNAKIADFGLSNMMSDGEFLRTSCGSPNYAAPEVISGRLYAGPEVDIWSSGVILYALLCGTLPFDDDHVPTLFKKICDGIFYTPQYLNPSVISLLKHMLQVDPMKRATIKDIREHEWFKQDLPKYLFPEDPSYSSTMIDDEALKEVCEKFECSEEEVLSCLYNRNHQDPLAVAYHLIIDNRRIMNEAKDFYLATSPPDSFLDDHHLTRPHPERVPFLVAETPRARHTLDELNPQKSKHQGVRKAKWHLGIRSQSRPNDIMAEVCRAIKQLDYEWKVVNPYYLRVRRKNPVTSTYSKMSLQLYQVDSRTYLLDFRSIDDELTPRPGSHTIEFFEMCANLIKILAQ,Homo sapiens,no,EVQLVESGGGLVQPGGSLRLSCAASGFNIYYYSIHWVRQAPGKGLEWVASIYPYSGSTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARYYPYFISYYSKMEAMDYWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSSGPITFGQGTKVEIK,GFNIYYY,YPYSGS,YYPYFISYYSKMEAMDY,RASQSVSSAVA,SASSLYS,QQSSSGPIT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSS,QMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK,True,7M74-10_127_141,EVQLVESGGGLVQPGGSLRLSCAASXXXXXXXSIHWVRQAPGKGLEWVASIXXXXXXTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARXXXXXXXXXXXXXXXXXWGQGTLVTVSSGGGGSGGGGSGGGGSQMTQSPSSLSASVGDRVTITCXXXXXXXXXXXWYQQKPGKAPKLLIYXXXXXXXGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCXXXXXXXXXFGQGTKVEIK
10,SabDab_nano,\,7O31,No,X-RAY DIFFRACTION,Crystal structure of the anti-PAS Fab 1.2 in complex with its epitope peptide and the anti-Kappa VHH domain,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,463058.0,100.0,anti-PAS Fab 1.2 chimeric heavy chain,1.0,A,L,NaN,NaN,463061.0,100.0,anti-PAS Fab 1.2 chimeric light chain,4.0,D,P,NaN,NaN,\,QAPASPAAPA,synthetic construct,no,EVQLVESGGGLVQPGGSLKLSCAASGFTFSSYGMSWVRQTPDKRLELVATINSNGGSTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRGGSIYDGYDYAMDYWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCRASQSVSTSSYSYMHWFQQKPGQPPKLLIKYASNLESGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCQHSWEIPLTFGAGTKLEIK,GFTFSSY,NSNGGS,GGSIYDGYDYAMDY,RASQSVSTSSYSYMH,YASNLES,QHSWEIPLT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGGLVQPGGSLKLSCAASXXXXXXXGMSWVRQTPDKRLELVATIXXXXXXTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRXXXXXXXXXXXXXXWGQGTSVTVSS,DIVLTQSPASLAVSLGQRATISCXXXXXXXXXXXXXXXWFQQKPGQPPKLLIKXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCXXXXXXXXXFGAGTKLEIK,True,7O31-11_124_138,EVQLVESGGGLVQPGGSLKLSCAASXXXXXXXGMSWVRQTPDKRLELVATIXXXXXXTYYLDSVKGRFTISRDKAKNTLYLQMSSLKSEDTAMYYCVRXXXXXXXXXXXXXXWGQGTSVTVSSGGGGSGGGGSGGGGSDIVLTQSPASLAVSLGQRATISCXXXXXXXXXXXXXXXWFQQKPGQPPKLLIKXXXXXXXGVPARFSGSGSGTDFTLNIHPVEEEDTATYYCXXXXXXXXXFGAGTKLEIK
11,SabDab_nano,\,7Q6C,No,X-RAY DIFFRACTION,complement C6 FIM1-2 bound to CP010 antibody,VRAI,scFv,Mus musculus,2.0,B,H,NaN,NaN,404023.0,100.0,CP010 heavy chain,4.0,D,L,NaN,NaN,404025.0,100.0,CP010 light chain,1.0,A,A,UniProt,P13671,\,LKGHCQLGQKQSGSECICMSPEEDCSHHSEDLCVFDTDSNDYFTSPACKFLAEKCLNNQQLHFLHIGSCQDGRQLEWGLERTRLSSASTKKESCGYDTCYDWEKCSASTSKCVCLLPPQCFKGGNQLYCVKMGSSTSEKTLNICEVGTIRCANRKMEILHPGKCLA,Homo sapiens,no,EVQLVESDGGLVQPGGSLKLSCAASGFTFSDYYMAWVRQGPGKGLEWVATINYDGSSTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARPSTEALFAYWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCRSSQSLLNDVGNTYLYWYLQKPGQSPQLLIYLVSDLGSGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCMQASHAPYTFGQGTNLEIK,GFTFSDY,NYDGSS,PSTEALFAY,RSSQSLLNDVGNTYLY,LVSDLGS,MQASHAPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESDGGLVQPGGSLKLSCAASXXXXXXXYMAWVRQGPGKGLEWVATIXXXXXXTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARXXXXXXXXXWGHGTLVTVSS,DVVLTQTPSTLSVTPGQPASISCXXXXXXXXXXXXXXXXWYLQKPGQSPQLLIYXXXXXXXGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCXXXXXXXXXFGQGTNLEIK,True,7Q6C-12_119_133,EVQLVESDGGLVQPGGSLKLSCAASXXXXXXXYMAWVRQGPGKGLEWVATIXXXXXXTYYRESVKGRFTISRDNAKNTLYLQMNSLRAEDTATYYCARXXXXXXXXXWGHGTLVTVSSGGGGSGGGGSGGGGSDVVLTQTPSTLSVTPGQPASISCXXXXXXXXXXXXXXXXWYLQKPGQSPQLLIYXXXXXXXGVPNRFSGSGSGTDFTLKISRVEAEDVGIYYCXXXXXXXXXFGQGTNLEIK

In [14]:
df_to_save.head(2)

,Source,Update_Date,PDB_ID,PDB_ID_Changed,Experimental_Method,Structure_Title,Complex_Structure,Ab_or_Nano,Source_Organism,H_Chain Entity ID,H_Chain Asym ID,H_Chain Auth Asym ID,H_Chain Database Name,H_Chain Accession Code(s),H_Chain Sequence Cluster ID,H_Chain Sequence Cluster Identity Threshold,H_Chain Macromolecule Name,L_Chain Entity ID,L_Chain Asym ID,L_Chain Auth Asym ID,L_Chain Database Name,L_Chain Accession Code(s),L_Chain Sequence Cluster ID,L_Chain Sequence Cluster Identity Threshold,L_Chain Macromolecule Name,Ag_Entity ID,Ag_Asym ID,Ag_Auth Asym ID,Ag_Database Name,Ag_Accession Code(s),Ag_Name,Ag_Seq,Ag_Source Organism,Ab/Nano_Mutation,Ab/Nano H_Chain AA,Ab/Nano L_Chain AA,Ab/Nano_CDR H1,Ab/Nano_CDR H2,Ab/Nano_CDR H3,Ab/Nano_CDR L1,Ab/Nano_CDR L2,Ab/Nano_CDR L3,CDR Nomenclature,"Affinity_Kd(M), (the near-physiological conditions, with controlled temperatures (20-25 °C or 37 °C) and buffered aqueous systems)","∆Gbinding(kJ/mol),(the near-equilibrium conditions at constant temperatures (20-25 °C) )",Affinity_Method,Reason_Code,Predicted_or_Not,Provenance,heavy_with_X,light_with_X,is_ok,id,seq_with_linker
0,SabDab_nano,\,3MLT,No,X-RAY DIFFRACTION,Crystal structure of anti-HIV-1 V3 Fab 2557 in complex with a UG1033 V3 peptide,VRAI,scFv,Homo sapiens,2.0,"B, E, H, J","B, E, H, I",NaN,NaN,17805.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab heavy chain,1.0,"A, D, G, I","A, D, G, L",NaN,NaN,34903.0,100.0,Human monoclonal anti-HIV-1 gp120 V3 antibody 2557 Fab light chain,NaN,NaN,NaN,NaN,NaN,hiv-1 gp120 third variable region (v3) crown,NNTRKSIHLGPGRAFYATGDIIG,unknown,no,EVQLVESGGEVKQPGQSLKISCKSSGYNFLDSWIGWVRQIPGKGLEWIGIIYPDDSDAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRLYLFEGAQSSNAFDLWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCSGDKLDDKYVSWYYQRPGQSPVLLMYQDFKRPSGIPERLSGSKSGKTATLTISGTQSLDEGDYYCQAWDASTGVSGGGTKLTVL,GYNFLDS,YPDDSD,LYLFEGAQSSNAFDL,SGDKLDDKYVS,QDFKRPS,QAWDASTGV,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSS,YDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL,True,3MLT-1_125_139,EVQLVESGGEVKQPGQSLKISCKSSXXXXXXXWIGWVRQIPGKGLEWIGIIXXXXXXAHYSPSFEGQVTMSVDKSISTAYLQWTTLQASDTGKYFCTRXXXXXXXXXXXXXXXWGQGTMILVSSGGGGSGGGGSGGGGSYDLTQPPSVSVSPGQTASISCXXXXXXXXXXXWYYQRPGQSPVLLMYXXXXXXXGIPERLSGSKSGKTATLTISGTQSLDEGDYYCXXXXXXXXXSGGGTKLTVL
1,SabDab_nano,\,3NID,No,X-RAY DIFFRACTION,The Closed Headpiece of Integrin alphaIIB beta3 and its Complex with an alpahIIB beta3 -Specific Antagonist That Does Not Induce Opening,VRAI,scFv,Mus musculus,3.0,"E, G","E, H",NaN,NaN,1268.0,100.0,Monoclonal antibody 10E5 heavy chain,4.0,"F, H","F, L",NaN,NaN,1019.0,100.0,Monoclonal antibody 10E5 light chain,1.0,"A, C","A, C",UniProt,P08514,integrin alpha-iib,LNLDPVQLTFYAGPNGSQFGFSLDFHKDSHGRVAIVVGAPRTLGPSQEETGGVFLCPWRAEGGQCPSLLFDLRDETRNVGSQTLQTFKARQGLGASVVSWSDVIVACAPWQHWNVLEKTEEAEKTPVGSCFLAQPESGRRAEYSPCRGNTLSRIYVENDFSWDKRYCEAGFSSVVTQAGELVLGAPGGYYFLGLLAQAPVADIFSSYRPGILLWHVSSQSLSFDSSNPEYFDGYWGYSVAVGEFDGDLNTTEYVVGAPTWSWTLGAVEILDSYYQRLHRLRGEQMASYFGHSVAVTDVNGDGRHDLLVGAPLYMESRADRKLAEVGRVYLFLQPRGPHALGAPSLLLTGTQLYGRFGSAIAPLGDLDRDGYNDIAVAAPYGGPSGRGQVLVFLGQSEGLRSRPSQVLDSPFPTGSAFGFSLRGAVDIDDNGYPDLIVGAYGANQVAVYRAQPVVKAS,Homo sapiens,no,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYVHWVKQRPEQGLEWIGRIDPANGYTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRPLYDYYAMDYWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCHASQGISSNIGWLQQKPGKSFMGLIYYGTNLVDGVPSRFSGSGSGADYSLTISSLDSEDFADYYCVQYAQLPYTFGGGTKLEIK,GFNIKDT,DPANGY,PLYDYYAMDY,HASQGISSNIG,YGTNLVD,VQYAQLPYT,Chothia,NaN,NaN,NaN,not_reported,\,SabDab_nano|PDB|schema_harmonisation,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSS,DILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK,True,3NID-2_120_134,EVQLQQSGAELVKPGASVKLSCTASXXXXXXXYVHWVKQRPEQGLEWIGRIXXXXXXTKYDPKFQGKATITADTSSNTAYLQLSSLTSEDTAVYYCVRXXXXXXXXXXWGQGTSVTVSSGGGGSGGGGSGGGGSDILMTQSPSSMSVSLGDTVSITCXXXXXXXXXXXWLQQKPGKSFMGLIYXXXXXXXGVPSRFSGSGSGADYSLTISSLDSEDFADYYCXXXXXXXXXFGGGTKLEIK

In [15]:
with open('scFv_templates.fasta', 'w') as f:
    for _, row in df_to_save.iterrows():
        f.write(f">{row['id']}\n{row['seq_with_linker']}\n")